## Default config file used by Github Pages, copy the config from one of the other config files to switch:
## _config-0g
## _config-1g
## _config-3g

repo: minvws/nl-covid19-notification-app-website

version: offline

collections:
  questions:
    output: false
    permalink: /:categories/:name/
  questions-in-app:
    output: false
    permalink: /:categories/:name/
  questions-scanner:
    output: false
    permalink: /:categories/:name/
  questions-scanner-in-app:
    output: false
    permalink: /:categories/:name/
  faqcategories:
    output: false
  faqcategories-in-app:
    output: false
  announcements:
    output: false

sass:
  style: compressed
  load_paths:
    - css

include:
  - .well-known

exclude:
  - vendor
  - print-portal
  - Gemfile
  - Gemfile.lock
  - CODE_OF_CONDUCT.md
  - README.md
  - README.announcements.md
  - README.content-translations.md
  - README.development.md
  - README.i18n.md
  - README.requirements.md
  - LICENSES.md
  - LICENSE.txt
  - LICENSE.pdf
  - example-content-page.md
  - .sass-cache
  - .history
  - auth.php
  - auth2.php
  - nl/faq.md
  - nl/faq-in-app.md
  - nl/faq-scanner.md
  - nl/faq-scanner-in-app.md
  - nl/wegwijzer
  - nl/wegwijzer-in-app
  - en/faq.md
  - en/faq-in-app.md
  - en/faq-scanner.md
  - en/faq-scanner-in-app.md
  - en/guidepost
  - en/guidepost-in-app
  - _questions
  - _questions-in-app
  - _questions-scanner
  - _questions-scanner-in-app
  - _faqcategories
  - _faqcategories-in-app

plugins:
  - "jekyll-github-metadata"
  - "jekyll-sitemap"
  - "jekyll-redirect-from"
  # - "jekyll-seo-tag"

incremental: false
